"""
GitHub tool — reads files and opens PRs on the Argus Agent repo.

PR strategy:
- One PR per agent domain (springboot, ml, react, infra, observability)
- Branch name: cortex/<agent>/<short-uuid>
- Draft PRs only — nothing merges without human approval
- Only opens PR if at least one finding in that domain is pr_ready=True
"""
import uuid
import base64
from datetime import datetime
from collections import defaultdict
from github import Github, GithubException
from config.settings import settings


def get_github_client() -> Github:
    return Github(settings.github_token)


def get_repo():
    g = get_github_client()
    return g.get_repo(f"{settings.github_org}/{settings.argus_repo}")


def read_file_from_github(file_path: str) -> tuple[str, str]:
    """
    Read a file from the Argus Agent GitHub repo.
    Returns (content, sha) — sha needed for updates.
    """
    repo = get_repo()
    try:
        file = repo.get_contents(file_path)
        content = base64.b64decode(file.content).decode("utf-8")
        return content, file.sha
    except GithubException as e:
        return f"[Error reading {file_path}: {e}]", ""


def create_pr_for_agent(
    agent_name: str,
    findings: list[dict],
    goal: str,
) -> str | None:
    """
    Create a draft PR on Argus Agent repo for a specific agent's findings.

    Returns the PR URL or None if no pr_ready findings.
    """
    pr_ready = [f for f in findings if f.get("pr_ready", False)]
    if not pr_ready:
        return None

    repo = get_repo()
    short_id = str(uuid.uuid4())[:8]
    branch_name = f"cortex/{agent_name}/{short_id}"
    base_branch = repo.default_branch

    # Get base branch SHA
    base_sha = repo.get_branch(base_branch).commit.sha

    # Create branch
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

    # Build PR body
    body = _build_pr_body(agent_name, pr_ready, goal)

    # Commit a findings summary file as proof-of-work
    # (Real code patches would go here when diff generation is added)
    summary_path = f".cortex/findings/{agent_name}/{short_id}.md"
    summary_content = _build_findings_markdown(agent_name, pr_ready, goal)

    try:
        repo.create_file(
            path=summary_path,
            message=f"cortex: {agent_name} findings — {short_id}",
            content=summary_content,
            branch=branch_name,
        )
    except GithubException as e:
        # Branch created but file commit failed — still open PR with body only
        pass

    # Open draft PR
    pr = repo.create_pull(
        title=f"[Argus Cortex] {agent_name}: {len(pr_ready)} finding(s) — {short_id}",
        body=body,
        head=branch_name,
        base=base_branch,
        draft=True,
    )

    return pr.html_url


def _build_pr_body(agent_name: str, findings: list[dict], goal: str) -> str:
    severity_emoji = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🟢",
    }

    lines = [
        f"## Argus Cortex — {agent_name}",
        f"",
        f"**Goal:** {goal}",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Findings:** {len(findings)}",
        f"",
        f"---",
        f"",
        f"## Findings",
        f"",
    ]

    for i, f in enumerate(findings, 1):
        emoji = severity_emoji.get(f.get("severity", "low"), "⚪")
        lines += [
            f"### {i}. {emoji} {f.get('severity', '').upper()} — {f.get('category', '')}",
            f"",
            f"**File:** `{f.get('file', '')}`" + (f" (line {f['line']})" if f.get("line") else ""),
            f"",
            f"**Issue:** {f.get('description', '')}",
            f"",
            f"**Fix:**",
            f"```",
            f"{f.get('suggested_fix', '')}",
            f"```",
            f"",
        ]

    lines += [
        "---",
        "",
        "> This is a **draft PR** generated by [Argus Cortex](https://github.com/ASREDDY03/argus-cortex).",
        "> Review all findings before merging. Nothing is auto-merged.",
    ]

    return "\n".join(lines)


def _build_findings_markdown(agent_name: str, findings: list[dict], goal: str) -> str:
    lines = [
        f"# {agent_name} Findings",
        f"Goal: {goal}",
        f"Date: {datetime.utcnow().isoformat()}",
        f"",
    ]
    for f in findings:
        lines.append(f"- [{f.get('severity')}] {f.get('file')} — {f.get('description')}")
    return "\n".join(lines)
